# Generated by Django 5.2.1 on 2025-06-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_add_missing_merchant_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicredential',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='api_secret_hash',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_registration',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='webhook_url',
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
