version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: phantom_banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phantom_banking
      - REDIS_URL=redis://redis:6379/0
      - VERIFF_API_KEY=${VERIFF_API_KEY}
      - VERIFF_API_SECRET=${VERIFF_API_SECRET}
      - VERIFF_WEBHOOK_SECRET=${VERIFF_WEBHOOK_SECRET}

  celery:
    build: .
    command: celery -A phantom_banking_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phantom_banking
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A phantom_banking_project beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/phantom_banking
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: