# Generated by Django 5.2.1 on 2025-06-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_eftpayment_paymentmethod_qrcode_transactionstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_wallet',
        ),
    ]
