# Generated by Django 5.2.1 on 2025-06-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_from_wallet_and_more'),
        ('wallets', '0002_wallet_is_kyc_verified_wallet_upgraded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='wallets.wallet'),
        ),
    ]
