# Generated by Django 5.2.1 on 2025-06-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('transactions', '0005_transaction_from_wallet_transaction_to_wallet'),
        ('wallets', '0003_restructure_independent_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('debit', 'Debit - Money leaving wallet'), ('credit', 'Credit - Money entering wallet')], default='debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant who initiated this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('qr_payment', 'QR Code Payment'), ('eft_topup', 'EFT Top-up'), ('wallet_transfer', 'Wallet Transfer'), ('merchant_payment', 'Merchant Payment'), ('merchant_credit', 'Merchant Credit'), ('merchant_debit', 'Merchant Debit'), ('refund', 'Refund'), ('fee', 'Transaction Fee'), ('payment', 'General Payment'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('topup', 'Wallet Top-up'), ('cashout', 'Cash Out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet'),
        ),
    ]
