# Generated by Django 5.2.1 on 2025-06-04 08:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=15)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='customers.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='merchants.merchant')),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
    ]
