# Generated by Django 5.2.1 on 2025-06-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
        ),
    ]
