# Generated by Django 5.2.1 on 2025-06-14 09:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_restructure_independent_customers'),
        ('merchants', '0001_initial'),
        ('wallets', '0002_wallet_is_kyc_verified_wallet_upgraded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='merchant',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_by_merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant who initially created this wallet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallets', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=15),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['customer'], name='wallets_custome_0488de_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='wallets_status_5720bd_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['created_by_merchant'], name='wallets_created_b5de78_idx'),
        ),
    ]
