# Generated by Django 5.2.1 on 2025-06-13 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('veriff_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('veriff_session_url', models.URLField(blank=True, null=True)),
                ('veriff_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('veriff_code', models.CharField(blank=True, max_length=10, null=True)),
                ('veriff_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission Requested')], default='pending', max_length=30)),
                ('verification_level', models.CharField(choices=[('basic', 'Basic'), ('enhanced', 'Enhanced'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=3)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=3)),
                ('document_front_image', models.URLField(blank=True, null=True)),
                ('document_back_image', models.URLField(blank=True, null=True)),
                ('selfie_image', models.URLField(blank=True, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('session_created', 'Session Created'), ('documents_uploaded', 'Documents Uploaded'), ('verification_started', 'Verification Started'), ('verification_completed', 'Verification Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kyc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kyc.kycrecord')),
            ],
            options={
                'db_table': 'kyc_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('driving_license', 'Driving License'), ('proof_of_address', 'Proof of Address'), ('bank_statement', 'Bank Statement')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('kyc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycrecord')),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
    ]
