# Generated by Django 5.2.1 on 2025-06-04 08:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('nationality', models.CharField(default='BW', max_length=50)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='merchants.merchant')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'unique_together': {('merchant', 'phone_number')},
            },
        ),
    ]
