# Generated by Django 5.2.1 on 2025-06-14 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCustomerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('full', 'Full Access - Can debit and credit'), ('credit_only', 'Credit Only - Can only add funds'), ('view_only', 'View Only - Can view balance only')], default='full', max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchant_customer_access',
            },
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet_created_by',
            field=models.ForeignKey(blank=True, help_text="Merchant who initially created this customer's wallet", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['identity_number'], name='customers_identit_03f5bb_idx'),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_access', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Merchant who granted this access (usually the wallet creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_access', to='merchants.merchant'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='merchant',
        ),
        migrations.AddIndex(
            model_name='merchantcustomeraccess',
            index=models.Index(fields=['merchant', 'customer'], name='merchant_cu_merchan_d94c74_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcustomeraccess',
            index=models.Index(fields=['customer', 'is_active'], name='merchant_cu_custome_1c7ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantcustomeraccess',
            index=models.Index(fields=['expires_at'], name='merchant_cu_expires_91aafa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merchantcustomeraccess',
            unique_together={('merchant', 'customer')},
        ),
    ]
