# Generated by Django 5.2.1 on 2025-06-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_restructure_independent_customers'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantcustomeraccess',
            name='granted_by',
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='created_by_merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant who created the wallet (auto-granted access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_granted_access', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='grant_reason',
            field=models.CharField(choices=[('wallet_creation', 'Wallet Creation - Automatic access for wallet creator'), ('business_partnership', 'Business Partnership - Admin approved partnership'), ('customer_request', 'Customer Request - Customer requested merchant access'), ('admin_grant', 'Admin Grant - Manual admin approval'), ('api_integration', 'API Integration - Technical integration approval')], default='wallet_creation', max_length=30),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='merchantcustomeraccess',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension (admin use)'),
        ),
        migrations.AlterField(
            model_name='merchantcustomeraccess',
            name='access_type',
            field=models.CharField(choices=[('full', 'Full Access - Can debit and credit'), ('credit_only', 'Credit Only - Can only add funds'), ('view_only', 'View Only - Can view balance only'), ('suspended', 'Suspended - No access (admin action)')], default='full', max_length=20),
        ),
    ]
