# Generated by Django 5.2.1 on 2025-06-12 12:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0006_alter_apicredential_options_remove_merchant_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('wallet_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('fnb', 'FNB Account')], default='basic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_transaction', models.DateTimeField(blank=True, null=True)),
                ('last_balance_update', models.DateTimeField(auto_now=True)),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=15)),
                ('monthly_transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('daily_transaction_count', models.PositiveIntegerField(default=0)),
                ('monthly_transaction_count', models.PositiveIntegerField(default=0)),
                ('daily_transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monthly_transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('merchant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_block_wallet', 'Can block wallet'), ('can_view_merchant_wallets', 'Can view merchant wallets'), ('can_manage_transaction_limits', 'Can manage transaction limits')],
            },
        ),
        migrations.CreateModel(
            name='WalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('block', 'Block'), ('unblock', 'Unblock'), ('limit_change', 'Limit Change'), ('type_change', 'Type Change')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreationRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_requests', to='merchants.merchant')),
            ],
        ),
    ]
